title: The Bread Code
author: Hendrik aka. The Bread Code
email: contact@the-bread-code.io # your email shown in the footer
url: https://blog.the-bread-code.io # this is your site's root address.
description: > # this means to ignore newlines until "show_excerpts:"
  Daytime Software developer and at nighttime mastering the art of baking 🍞.
  Follow me on my journey to becoming a skilled baker. This blog is dedicated to
  sharing my learning progress.
favicon: "./favicon.ico" # set the favicon of the site

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap